version: '3.9'

networks:
  default:
    name: trpy
    external: false

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  api:
    image: trpy-api:latest
    container_name: trpy-api
    restart: always
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '${ASPNETCORE_HTTP_PORT}:7000'
      - '${ASPNETCORE_HTTPS_PORT}:7001'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    build:
      context: .
      target: runtime
      dockerfile: ./src/TelegramBotPrototype/Dockerfile
      args:
        - CONFIGURATION=${ASPNETCORE_CONFIGURATION}
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: http://+:${ASPNETCORE_HTTP_PORT};https://+:${ASPNETCORE_HTTPS_PORT}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/dev.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: development
    volumes:
      - ./https:/https:ro
      - ./src/TelegramBotPrototype/appsettings.json:/srv/appsettings.json:ro
      - ./src/TelegramBotPrototype/appsettings.Development.json:/srv/appsettings.Development.json:ro
